//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Proyecto_APSNET.otrowebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="otrowebservicePortBinding", Namespace="http://webservice/")]
    public partial class otrowebservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ELIMINARUSTAROperationCompleted;
        
        private System.Threading.SendOrPostCallback ELIMINARTAREAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ELIMINARPROYECTOOperationCompleted;
        
        private System.Threading.SendOrPostCallback ELIMINARUSPROYOperationCompleted;
        
        private System.Threading.SendOrPostCallback ELIMINARESTADODELCOMENTARIOOperationCompleted;
        
        private System.Threading.SendOrPostCallback ELIMINARESTADODEFINITIVOOperationCompleted;
        
        private System.Threading.SendOrPostCallback ELIMINARPROYLISTATAREAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ELIMINARCOMENTARIOOperationCompleted;
        
        private System.Threading.SendOrPostCallback ELIMINARTARLISTATAREAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public otrowebservice() {
            this.Url = global::Proyecto_APSNET.Properties.Settings.Default.Proyecto_APSNET_otrowebservice_otrowebservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ELIMINARUSTARCompletedEventHandler ELIMINARUSTARCompleted;
        
        /// <remarks/>
        public event ELIMINARTAREACompletedEventHandler ELIMINARTAREACompleted;
        
        /// <remarks/>
        public event ELIMINARPROYECTOCompletedEventHandler ELIMINARPROYECTOCompleted;
        
        /// <remarks/>
        public event ELIMINARUSPROYCompletedEventHandler ELIMINARUSPROYCompleted;
        
        /// <remarks/>
        public event ELIMINARESTADODELCOMENTARIOCompletedEventHandler ELIMINARESTADODELCOMENTARIOCompleted;
        
        /// <remarks/>
        public event ELIMINARESTADODEFINITIVOCompletedEventHandler ELIMINARESTADODEFINITIVOCompleted;
        
        /// <remarks/>
        public event ELIMINARPROYLISTATAREACompletedEventHandler ELIMINARPROYLISTATAREACompleted;
        
        /// <remarks/>
        public event ELIMINARCOMENTARIOCompletedEventHandler ELIMINARCOMENTARIOCompleted;
        
        /// <remarks/>
        public event ELIMINARTARLISTATAREACompletedEventHandler ELIMINARTARLISTATAREACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ELIMINARUSTAR([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int Tarea) {
            object[] results = this.Invoke("ELIMINARUSTAR", new object[] {
                        Tarea});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ELIMINARUSTARAsync(int Tarea) {
            this.ELIMINARUSTARAsync(Tarea, null);
        }
        
        /// <remarks/>
        public void ELIMINARUSTARAsync(int Tarea, object userState) {
            if ((this.ELIMINARUSTAROperationCompleted == null)) {
                this.ELIMINARUSTAROperationCompleted = new System.Threading.SendOrPostCallback(this.OnELIMINARUSTAROperationCompleted);
            }
            this.InvokeAsync("ELIMINARUSTAR", new object[] {
                        Tarea}, this.ELIMINARUSTAROperationCompleted, userState);
        }
        
        private void OnELIMINARUSTAROperationCompleted(object arg) {
            if ((this.ELIMINARUSTARCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ELIMINARUSTARCompleted(this, new ELIMINARUSTARCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ELIMINARTAREA([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int Tarea) {
            object[] results = this.Invoke("ELIMINARTAREA", new object[] {
                        Tarea});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ELIMINARTAREAAsync(int Tarea) {
            this.ELIMINARTAREAAsync(Tarea, null);
        }
        
        /// <remarks/>
        public void ELIMINARTAREAAsync(int Tarea, object userState) {
            if ((this.ELIMINARTAREAOperationCompleted == null)) {
                this.ELIMINARTAREAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnELIMINARTAREAOperationCompleted);
            }
            this.InvokeAsync("ELIMINARTAREA", new object[] {
                        Tarea}, this.ELIMINARTAREAOperationCompleted, userState);
        }
        
        private void OnELIMINARTAREAOperationCompleted(object arg) {
            if ((this.ELIMINARTAREACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ELIMINARTAREACompleted(this, new ELIMINARTAREACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ELIMINARPROYECTO([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int Proyecto) {
            object[] results = this.Invoke("ELIMINARPROYECTO", new object[] {
                        Proyecto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ELIMINARPROYECTOAsync(int Proyecto) {
            this.ELIMINARPROYECTOAsync(Proyecto, null);
        }
        
        /// <remarks/>
        public void ELIMINARPROYECTOAsync(int Proyecto, object userState) {
            if ((this.ELIMINARPROYECTOOperationCompleted == null)) {
                this.ELIMINARPROYECTOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnELIMINARPROYECTOOperationCompleted);
            }
            this.InvokeAsync("ELIMINARPROYECTO", new object[] {
                        Proyecto}, this.ELIMINARPROYECTOOperationCompleted, userState);
        }
        
        private void OnELIMINARPROYECTOOperationCompleted(object arg) {
            if ((this.ELIMINARPROYECTOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ELIMINARPROYECTOCompleted(this, new ELIMINARPROYECTOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ELIMINARUSPROY([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int Proyecto) {
            object[] results = this.Invoke("ELIMINARUSPROY", new object[] {
                        Proyecto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ELIMINARUSPROYAsync(int Proyecto) {
            this.ELIMINARUSPROYAsync(Proyecto, null);
        }
        
        /// <remarks/>
        public void ELIMINARUSPROYAsync(int Proyecto, object userState) {
            if ((this.ELIMINARUSPROYOperationCompleted == null)) {
                this.ELIMINARUSPROYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnELIMINARUSPROYOperationCompleted);
            }
            this.InvokeAsync("ELIMINARUSPROY", new object[] {
                        Proyecto}, this.ELIMINARUSPROYOperationCompleted, userState);
        }
        
        private void OnELIMINARUSPROYOperationCompleted(object arg) {
            if ((this.ELIMINARUSPROYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ELIMINARUSPROYCompleted(this, new ELIMINARUSPROYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ELIMINARESTADODELCOMENTARIO([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int Estado) {
            object[] results = this.Invoke("ELIMINARESTADODELCOMENTARIO", new object[] {
                        Estado});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ELIMINARESTADODELCOMENTARIOAsync(int Estado) {
            this.ELIMINARESTADODELCOMENTARIOAsync(Estado, null);
        }
        
        /// <remarks/>
        public void ELIMINARESTADODELCOMENTARIOAsync(int Estado, object userState) {
            if ((this.ELIMINARESTADODELCOMENTARIOOperationCompleted == null)) {
                this.ELIMINARESTADODELCOMENTARIOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnELIMINARESTADODELCOMENTARIOOperationCompleted);
            }
            this.InvokeAsync("ELIMINARESTADODELCOMENTARIO", new object[] {
                        Estado}, this.ELIMINARESTADODELCOMENTARIOOperationCompleted, userState);
        }
        
        private void OnELIMINARESTADODELCOMENTARIOOperationCompleted(object arg) {
            if ((this.ELIMINARESTADODELCOMENTARIOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ELIMINARESTADODELCOMENTARIOCompleted(this, new ELIMINARESTADODELCOMENTARIOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ELIMINARESTADODEFINITIVO([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int Estado) {
            object[] results = this.Invoke("ELIMINARESTADODEFINITIVO", new object[] {
                        Estado});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ELIMINARESTADODEFINITIVOAsync(int Estado) {
            this.ELIMINARESTADODEFINITIVOAsync(Estado, null);
        }
        
        /// <remarks/>
        public void ELIMINARESTADODEFINITIVOAsync(int Estado, object userState) {
            if ((this.ELIMINARESTADODEFINITIVOOperationCompleted == null)) {
                this.ELIMINARESTADODEFINITIVOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnELIMINARESTADODEFINITIVOOperationCompleted);
            }
            this.InvokeAsync("ELIMINARESTADODEFINITIVO", new object[] {
                        Estado}, this.ELIMINARESTADODEFINITIVOOperationCompleted, userState);
        }
        
        private void OnELIMINARESTADODEFINITIVOOperationCompleted(object arg) {
            if ((this.ELIMINARESTADODEFINITIVOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ELIMINARESTADODEFINITIVOCompleted(this, new ELIMINARESTADODEFINITIVOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ELIMINARPROYLISTATAREA([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int Proyecto) {
            object[] results = this.Invoke("ELIMINARPROYLISTATAREA", new object[] {
                        Proyecto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ELIMINARPROYLISTATAREAAsync(int Proyecto) {
            this.ELIMINARPROYLISTATAREAAsync(Proyecto, null);
        }
        
        /// <remarks/>
        public void ELIMINARPROYLISTATAREAAsync(int Proyecto, object userState) {
            if ((this.ELIMINARPROYLISTATAREAOperationCompleted == null)) {
                this.ELIMINARPROYLISTATAREAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnELIMINARPROYLISTATAREAOperationCompleted);
            }
            this.InvokeAsync("ELIMINARPROYLISTATAREA", new object[] {
                        Proyecto}, this.ELIMINARPROYLISTATAREAOperationCompleted, userState);
        }
        
        private void OnELIMINARPROYLISTATAREAOperationCompleted(object arg) {
            if ((this.ELIMINARPROYLISTATAREACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ELIMINARPROYLISTATAREACompleted(this, new ELIMINARPROYLISTATAREACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ELIMINARCOMENTARIO([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int Comentario) {
            object[] results = this.Invoke("ELIMINARCOMENTARIO", new object[] {
                        Comentario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ELIMINARCOMENTARIOAsync(int Comentario) {
            this.ELIMINARCOMENTARIOAsync(Comentario, null);
        }
        
        /// <remarks/>
        public void ELIMINARCOMENTARIOAsync(int Comentario, object userState) {
            if ((this.ELIMINARCOMENTARIOOperationCompleted == null)) {
                this.ELIMINARCOMENTARIOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnELIMINARCOMENTARIOOperationCompleted);
            }
            this.InvokeAsync("ELIMINARCOMENTARIO", new object[] {
                        Comentario}, this.ELIMINARCOMENTARIOOperationCompleted, userState);
        }
        
        private void OnELIMINARCOMENTARIOOperationCompleted(object arg) {
            if ((this.ELIMINARCOMENTARIOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ELIMINARCOMENTARIOCompleted(this, new ELIMINARCOMENTARIOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ELIMINARTARLISTATAREA([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int Tarea) {
            object[] results = this.Invoke("ELIMINARTARLISTATAREA", new object[] {
                        Tarea});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ELIMINARTARLISTATAREAAsync(int Tarea) {
            this.ELIMINARTARLISTATAREAAsync(Tarea, null);
        }
        
        /// <remarks/>
        public void ELIMINARTARLISTATAREAAsync(int Tarea, object userState) {
            if ((this.ELIMINARTARLISTATAREAOperationCompleted == null)) {
                this.ELIMINARTARLISTATAREAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnELIMINARTARLISTATAREAOperationCompleted);
            }
            this.InvokeAsync("ELIMINARTARLISTATAREA", new object[] {
                        Tarea}, this.ELIMINARTARLISTATAREAOperationCompleted, userState);
        }
        
        private void OnELIMINARTARLISTATAREAOperationCompleted(object arg) {
            if ((this.ELIMINARTARLISTATAREACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ELIMINARTARLISTATAREACompleted(this, new ELIMINARTARLISTATAREACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ELIMINARUSTARCompletedEventHandler(object sender, ELIMINARUSTARCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ELIMINARUSTARCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ELIMINARUSTARCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ELIMINARTAREACompletedEventHandler(object sender, ELIMINARTAREACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ELIMINARTAREACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ELIMINARTAREACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ELIMINARPROYECTOCompletedEventHandler(object sender, ELIMINARPROYECTOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ELIMINARPROYECTOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ELIMINARPROYECTOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ELIMINARUSPROYCompletedEventHandler(object sender, ELIMINARUSPROYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ELIMINARUSPROYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ELIMINARUSPROYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ELIMINARESTADODELCOMENTARIOCompletedEventHandler(object sender, ELIMINARESTADODELCOMENTARIOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ELIMINARESTADODELCOMENTARIOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ELIMINARESTADODELCOMENTARIOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ELIMINARESTADODEFINITIVOCompletedEventHandler(object sender, ELIMINARESTADODEFINITIVOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ELIMINARESTADODEFINITIVOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ELIMINARESTADODEFINITIVOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ELIMINARPROYLISTATAREACompletedEventHandler(object sender, ELIMINARPROYLISTATAREACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ELIMINARPROYLISTATAREACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ELIMINARPROYLISTATAREACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ELIMINARCOMENTARIOCompletedEventHandler(object sender, ELIMINARCOMENTARIOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ELIMINARCOMENTARIOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ELIMINARCOMENTARIOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ELIMINARTARLISTATAREACompletedEventHandler(object sender, ELIMINARTARLISTATAREACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ELIMINARTARLISTATAREACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ELIMINARTARLISTATAREACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591