CREATE TABLE USUARIO(
ID_US INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
CORREO VARCHAR(50) NOT NULL,
NACIMIENTO DATE NOT NULL,
CONTRASEÑA VARCHAR(50) NOT NULL,
USERNAME VARCHAR(10) NOT NULL
)
ENGINE=InnoDB
;

CREATE TABLE ASOCIACION(
ID_ASO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
OBJETIVO VARCHAR(50) NOT NULL,
LOGO BLOB NOT NULL
)
ENGINE=InnoDB
;

CREATE TABLE US_ASO(
ID_DUA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_US INT NOT NULL,
FOREIGN KEY (ID_US) REFERENCES USUARIO(ID_US)
ON DELETE CASCADE ON UPDATE CASCADE,
ID_ASO INT NOT NULL,
FOREIGN KEY (ID_ASO) REFERENCES ASOCIACION(ID_ASO)
ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
;

CREATE TABLE HABILIDAD(
ID_HAB INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DESCRIPCION VARCHAR(50) NOT NULL
)
ENGINE=InnoDB
;

CREATE TABLE US_HAB(
ID_DUH INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
KARMA_P INT NOT NULL,
KARMA_N INT NOT NULL,
ID_US INT NOT NULL,
FOREIGN KEY (ID_US) REFERENCES USUARIO(ID_US)
ON DELETE CASCADE ON UPDATE CASCADE,
ID_HAB INT NOT NULL,
FOREIGN KEY (ID_HAB) REFERENCES HABILIDAD(ID_HAB)
ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
;

CREATE TABLE CONOCIMIENTO(
ID_CON INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DESCRIPCION VARCHAR(50) NOT NULL
)
ENGINE=InnoDB
;

CREATE TABLE US_CON(
ID_DUC INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
KARMA_P INT NOT NULL,
KARMA_N INT NOT NULL,
ID_US INT NOT NULL,
FOREIGN KEY (ID_US) REFERENCES USUARIO(ID_US)
ON DELETE CASCADE ON UPDATE CASCADE,
ID_CON INT NOT NULL,
FOREIGN KEY (ID_CON) REFERENCES CONOCIMIENTO(ID_CON)
ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
;

CREATE TABLE HAB_CON(
ID_DHC INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_HAB INT NOT NULL,
FOREIGN KEY (ID_HAB) REFERENCES HABILIDAD(ID_HAB)
ON DELETE CASCADE ON UPDATE CASCADE,
ID_CON INT NOT NULL,
FOREIGN KEY (ID_CON) REFERENCES CONOCIMIENTO(ID_CON)
ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
;

CREATE TABLE CONTACTO(
ID_CONTACTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
MENSAJE VARCHAR(50) NOT NULL,
ID_US INT NOT NULL,
FOREIGN KEY (ID_US) REFERENCES USUARIO(ID_US)
ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
;

CREATE TABLE ESTADO(
ID_EST INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
MENSAJE VARCHAR(50) NOT NULL,
ID_US INT NOT NULL,
FOREIGN KEY (ID_US) REFERENCES USUARIO(ID_US)
ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
;

CREATE TABLE COMENTARIO(
ID_COM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
MENSAJE VARCHAR(50) NOT NULL,
ID_US INT NOT NULL,
FOREIGN KEY (ID_US) REFERENCES USUARIO(ID_US)
ON DELETE CASCADE ON UPDATE CASCADE,
ID_EST INT NOT NULL,
FOREIGN KEY (ID_EST) REFERENCES ESTADO(ID_EST)
ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
;

CREATE TABLE PROYECTO(
ID_PROY INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
FEHCA_I DATE NOT NULL
)
ENGINE=InnoDB
;

CREATE TABLE US_PROY(
ID_DUP INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_US INT NOT NULL,
FOREIGN KEY (ID_US) REFERENCES USUARIO(ID_US)
ON DELETE CASCADE ON UPDATE CASCADE,
ID_PROY INT NOT NULL,
FOREIGN KEY (ID_PROY) REFERENCES PROYECTO(ID_PROY)
ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
;

CREATE TABLE TAREA(
ID_TAR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(50) NOT NULL,
FEHCA_I DATE NOT NULL
)
ENGINE=InnoDB
;

CREATE TABLE LISTA_TAREA(
ID_LT INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_PROY INT NOT NULL,
FOREIGN KEY (ID_PROY) REFERENCES PROYECTO(ID_PROY)
ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
;

CREATE TABLE DET_LT(
ID_DLT INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_LT INT NOT NULL,
FOREIGN KEY (ID_LT) REFERENCES LISTA_TAREA(ID_LT)
ON DELETE CASCADE ON UPDATE CASCADE,
ID_TAR INT NOT NULL,
FOREIGN KEY (ID_TAR) REFERENCES TAREA(ID_TAR)
ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
;

CREATE TABLE LISTA_CON(
ID_LC INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_TAR INT NOT NULL,
FOREIGN KEY (ID_TAR) REFERENCES TAREA(ID_TAR)
ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
;

CREATE TABLE DET_LC(
ID_DLC INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_LC INT NOT NULL,
FOREIGN KEY (ID_LC) REFERENCES LISTA_CON(ID_LC)
ON DELETE CASCADE ON UPDATE CASCADE,
ID_CON INT NOT NULL,
FOREIGN KEY (ID_CON) REFERENCES CONOCIMIENTO(ID_CON)
ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
;