//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Proyecto_APSNET.webservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="webservicePortBinding", Namespace="http://webservice/")]
    public partial class webservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback USPROYOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarseOperationCompleted;
        
        private System.Threading.SendOrPostCallback IniciarSesionOperationCompleted;
        
        private System.Threading.SendOrPostCallback PublicarEstadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerIDEstOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerIDUSOperationCompleted;
        
        private System.Threading.SendOrPostCallback desplegarEstadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback BackupUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback BackupAsoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PublicarComentarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback desplegarUSOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearListaTAREAOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearTareaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearProyectoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerTareaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerProyectoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public webservice() {
            this.Url = global::Proyecto_APSNET.Properties.Settings.Default.Proyecto_APSNET_webservice_webservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event USPROYCompletedEventHandler USPROYCompleted;
        
        /// <remarks/>
        public event RegistrarseCompletedEventHandler RegistrarseCompleted;
        
        /// <remarks/>
        public event IniciarSesionCompletedEventHandler IniciarSesionCompleted;
        
        /// <remarks/>
        public event PublicarEstadoCompletedEventHandler PublicarEstadoCompleted;
        
        /// <remarks/>
        public event obtenerIDEstCompletedEventHandler obtenerIDEstCompleted;
        
        /// <remarks/>
        public event obtenerIDUSCompletedEventHandler obtenerIDUSCompleted;
        
        /// <remarks/>
        public event desplegarEstadosCompletedEventHandler desplegarEstadosCompleted;
        
        /// <remarks/>
        public event BackupUsuariosCompletedEventHandler BackupUsuariosCompleted;
        
        /// <remarks/>
        public event BackupAsoCompletedEventHandler BackupAsoCompleted;
        
        /// <remarks/>
        public event PublicarComentarioCompletedEventHandler PublicarComentarioCompleted;
        
        /// <remarks/>
        public event desplegarUSCompletedEventHandler desplegarUSCompleted;
        
        /// <remarks/>
        public event CrearListaTAREACompletedEventHandler CrearListaTAREACompleted;
        
        /// <remarks/>
        public event CrearTareaCompletedEventHandler CrearTareaCompleted;
        
        /// <remarks/>
        public event CrearProyectoCompletedEventHandler CrearProyectoCompleted;
        
        /// <remarks/>
        public event ObtenerTareaCompletedEventHandler ObtenerTareaCompleted;
        
        /// <remarks/>
        public event ObtenerProyectoCompletedEventHandler ObtenerProyectoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool USPROY([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int Id_us, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int Id_proy) {
            object[] results = this.Invoke("USPROY", new object[] {
                        Id_us,
                        Id_proy});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void USPROYAsync(int Id_us, int Id_proy) {
            this.USPROYAsync(Id_us, Id_proy, null);
        }
        
        /// <remarks/>
        public void USPROYAsync(int Id_us, int Id_proy, object userState) {
            if ((this.USPROYOperationCompleted == null)) {
                this.USPROYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUSPROYOperationCompleted);
            }
            this.InvokeAsync("USPROY", new object[] {
                        Id_us,
                        Id_proy}, this.USPROYOperationCompleted, userState);
        }
        
        private void OnUSPROYOperationCompleted(object arg) {
            if ((this.USPROYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.USPROYCompleted(this, new USPROYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Registrarse([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Nombre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Apellido, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Nacimiento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Correo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Contra) {
            object[] results = this.Invoke("Registrarse", new object[] {
                        Usuario,
                        Nombre,
                        Apellido,
                        Nacimiento,
                        Correo,
                        Contra});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarseAsync(string Usuario, string Nombre, string Apellido, string Nacimiento, string Correo, string Contra) {
            this.RegistrarseAsync(Usuario, Nombre, Apellido, Nacimiento, Correo, Contra, null);
        }
        
        /// <remarks/>
        public void RegistrarseAsync(string Usuario, string Nombre, string Apellido, string Nacimiento, string Correo, string Contra, object userState) {
            if ((this.RegistrarseOperationCompleted == null)) {
                this.RegistrarseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarseOperationCompleted);
            }
            this.InvokeAsync("Registrarse", new object[] {
                        Usuario,
                        Nombre,
                        Apellido,
                        Nacimiento,
                        Correo,
                        Contra}, this.RegistrarseOperationCompleted, userState);
        }
        
        private void OnRegistrarseOperationCompleted(object arg) {
            if ((this.RegistrarseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarseCompleted(this, new RegistrarseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IniciarSesion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Contra) {
            object[] results = this.Invoke("IniciarSesion", new object[] {
                        Usuario,
                        Contra});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IniciarSesionAsync(string Usuario, string Contra) {
            this.IniciarSesionAsync(Usuario, Contra, null);
        }
        
        /// <remarks/>
        public void IniciarSesionAsync(string Usuario, string Contra, object userState) {
            if ((this.IniciarSesionOperationCompleted == null)) {
                this.IniciarSesionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIniciarSesionOperationCompleted);
            }
            this.InvokeAsync("IniciarSesion", new object[] {
                        Usuario,
                        Contra}, this.IniciarSesionOperationCompleted, userState);
        }
        
        private void OnIniciarSesionOperationCompleted(object arg) {
            if ((this.IniciarSesionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IniciarSesionCompleted(this, new IniciarSesionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool PublicarEstado([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Mensaje, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int IdUs) {
            object[] results = this.Invoke("PublicarEstado", new object[] {
                        Mensaje,
                        IdUs});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PublicarEstadoAsync(string Mensaje, int IdUs) {
            this.PublicarEstadoAsync(Mensaje, IdUs, null);
        }
        
        /// <remarks/>
        public void PublicarEstadoAsync(string Mensaje, int IdUs, object userState) {
            if ((this.PublicarEstadoOperationCompleted == null)) {
                this.PublicarEstadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPublicarEstadoOperationCompleted);
            }
            this.InvokeAsync("PublicarEstado", new object[] {
                        Mensaje,
                        IdUs}, this.PublicarEstadoOperationCompleted, userState);
        }
        
        private void OnPublicarEstadoOperationCompleted(object arg) {
            if ((this.PublicarEstadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PublicarEstadoCompleted(this, new PublicarEstadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int obtenerIDEst([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Mensaje) {
            object[] results = this.Invoke("obtenerIDEst", new object[] {
                        Mensaje});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerIDEstAsync(string Mensaje) {
            this.obtenerIDEstAsync(Mensaje, null);
        }
        
        /// <remarks/>
        public void obtenerIDEstAsync(string Mensaje, object userState) {
            if ((this.obtenerIDEstOperationCompleted == null)) {
                this.obtenerIDEstOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerIDEstOperationCompleted);
            }
            this.InvokeAsync("obtenerIDEst", new object[] {
                        Mensaje}, this.obtenerIDEstOperationCompleted, userState);
        }
        
        private void OnobtenerIDEstOperationCompleted(object arg) {
            if ((this.obtenerIDEstCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerIDEstCompleted(this, new obtenerIDEstCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int obtenerIDUS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Usuario) {
            object[] results = this.Invoke("obtenerIDUS", new object[] {
                        Usuario});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerIDUSAsync(string Usuario) {
            this.obtenerIDUSAsync(Usuario, null);
        }
        
        /// <remarks/>
        public void obtenerIDUSAsync(string Usuario, object userState) {
            if ((this.obtenerIDUSOperationCompleted == null)) {
                this.obtenerIDUSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerIDUSOperationCompleted);
            }
            this.InvokeAsync("obtenerIDUS", new object[] {
                        Usuario}, this.obtenerIDUSOperationCompleted, userState);
        }
        
        private void OnobtenerIDUSOperationCompleted(object arg) {
            if ((this.obtenerIDUSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerIDUSCompleted(this, new obtenerIDUSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string desplegarEstados() {
            object[] results = this.Invoke("desplegarEstados", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void desplegarEstadosAsync() {
            this.desplegarEstadosAsync(null);
        }
        
        /// <remarks/>
        public void desplegarEstadosAsync(object userState) {
            if ((this.desplegarEstadosOperationCompleted == null)) {
                this.desplegarEstadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OndesplegarEstadosOperationCompleted);
            }
            this.InvokeAsync("desplegarEstados", new object[0], this.desplegarEstadosOperationCompleted, userState);
        }
        
        private void OndesplegarEstadosOperationCompleted(object arg) {
            if ((this.desplegarEstadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.desplegarEstadosCompleted(this, new desplegarEstadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool BackupUsuarios() {
            object[] results = this.Invoke("BackupUsuarios", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void BackupUsuariosAsync() {
            this.BackupUsuariosAsync(null);
        }
        
        /// <remarks/>
        public void BackupUsuariosAsync(object userState) {
            if ((this.BackupUsuariosOperationCompleted == null)) {
                this.BackupUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBackupUsuariosOperationCompleted);
            }
            this.InvokeAsync("BackupUsuarios", new object[0], this.BackupUsuariosOperationCompleted, userState);
        }
        
        private void OnBackupUsuariosOperationCompleted(object arg) {
            if ((this.BackupUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BackupUsuariosCompleted(this, new BackupUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool BackupAso() {
            object[] results = this.Invoke("BackupAso", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void BackupAsoAsync() {
            this.BackupAsoAsync(null);
        }
        
        /// <remarks/>
        public void BackupAsoAsync(object userState) {
            if ((this.BackupAsoOperationCompleted == null)) {
                this.BackupAsoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBackupAsoOperationCompleted);
            }
            this.InvokeAsync("BackupAso", new object[0], this.BackupAsoOperationCompleted, userState);
        }
        
        private void OnBackupAsoOperationCompleted(object arg) {
            if ((this.BackupAsoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BackupAsoCompleted(this, new BackupAsoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool PublicarComentario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Mensaje, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int IdUs, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int IdEst) {
            object[] results = this.Invoke("PublicarComentario", new object[] {
                        Mensaje,
                        IdUs,
                        IdEst});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PublicarComentarioAsync(string Mensaje, int IdUs, int IdEst) {
            this.PublicarComentarioAsync(Mensaje, IdUs, IdEst, null);
        }
        
        /// <remarks/>
        public void PublicarComentarioAsync(string Mensaje, int IdUs, int IdEst, object userState) {
            if ((this.PublicarComentarioOperationCompleted == null)) {
                this.PublicarComentarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPublicarComentarioOperationCompleted);
            }
            this.InvokeAsync("PublicarComentario", new object[] {
                        Mensaje,
                        IdUs,
                        IdEst}, this.PublicarComentarioOperationCompleted, userState);
        }
        
        private void OnPublicarComentarioOperationCompleted(object arg) {
            if ((this.PublicarComentarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PublicarComentarioCompleted(this, new PublicarComentarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string desplegarUS() {
            object[] results = this.Invoke("desplegarUS", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void desplegarUSAsync() {
            this.desplegarUSAsync(null);
        }
        
        /// <remarks/>
        public void desplegarUSAsync(object userState) {
            if ((this.desplegarUSOperationCompleted == null)) {
                this.desplegarUSOperationCompleted = new System.Threading.SendOrPostCallback(this.OndesplegarUSOperationCompleted);
            }
            this.InvokeAsync("desplegarUS", new object[0], this.desplegarUSOperationCompleted, userState);
        }
        
        private void OndesplegarUSOperationCompleted(object arg) {
            if ((this.desplegarUSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.desplegarUSCompleted(this, new desplegarUSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CrearListaTAREA([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int Id_proy, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int Id_tar) {
            object[] results = this.Invoke("CrearListaTAREA", new object[] {
                        Id_proy,
                        Id_tar});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CrearListaTAREAAsync(int Id_proy, int Id_tar) {
            this.CrearListaTAREAAsync(Id_proy, Id_tar, null);
        }
        
        /// <remarks/>
        public void CrearListaTAREAAsync(int Id_proy, int Id_tar, object userState) {
            if ((this.CrearListaTAREAOperationCompleted == null)) {
                this.CrearListaTAREAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearListaTAREAOperationCompleted);
            }
            this.InvokeAsync("CrearListaTAREA", new object[] {
                        Id_proy,
                        Id_tar}, this.CrearListaTAREAOperationCompleted, userState);
        }
        
        private void OnCrearListaTAREAOperationCompleted(object arg) {
            if ((this.CrearListaTAREACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearListaTAREACompleted(this, new CrearListaTAREACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CrearTarea([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Nombre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Descripcion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Fecha) {
            object[] results = this.Invoke("CrearTarea", new object[] {
                        Nombre,
                        Descripcion,
                        Fecha});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CrearTareaAsync(string Nombre, string Descripcion, string Fecha) {
            this.CrearTareaAsync(Nombre, Descripcion, Fecha, null);
        }
        
        /// <remarks/>
        public void CrearTareaAsync(string Nombre, string Descripcion, string Fecha, object userState) {
            if ((this.CrearTareaOperationCompleted == null)) {
                this.CrearTareaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearTareaOperationCompleted);
            }
            this.InvokeAsync("CrearTarea", new object[] {
                        Nombre,
                        Descripcion,
                        Fecha}, this.CrearTareaOperationCompleted, userState);
        }
        
        private void OnCrearTareaOperationCompleted(object arg) {
            if ((this.CrearTareaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearTareaCompleted(this, new CrearTareaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CrearProyecto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Nombre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Fecha) {
            object[] results = this.Invoke("CrearProyecto", new object[] {
                        Nombre,
                        Fecha});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CrearProyectoAsync(string Nombre, string Fecha) {
            this.CrearProyectoAsync(Nombre, Fecha, null);
        }
        
        /// <remarks/>
        public void CrearProyectoAsync(string Nombre, string Fecha, object userState) {
            if ((this.CrearProyectoOperationCompleted == null)) {
                this.CrearProyectoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearProyectoOperationCompleted);
            }
            this.InvokeAsync("CrearProyecto", new object[] {
                        Nombre,
                        Fecha}, this.CrearProyectoOperationCompleted, userState);
        }
        
        private void OnCrearProyectoOperationCompleted(object arg) {
            if ((this.CrearProyectoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearProyectoCompleted(this, new CrearProyectoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ObtenerTarea([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Nombre) {
            object[] results = this.Invoke("ObtenerTarea", new object[] {
                        Nombre});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerTareaAsync(string Nombre) {
            this.ObtenerTareaAsync(Nombre, null);
        }
        
        /// <remarks/>
        public void ObtenerTareaAsync(string Nombre, object userState) {
            if ((this.ObtenerTareaOperationCompleted == null)) {
                this.ObtenerTareaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerTareaOperationCompleted);
            }
            this.InvokeAsync("ObtenerTarea", new object[] {
                        Nombre}, this.ObtenerTareaOperationCompleted, userState);
        }
        
        private void OnObtenerTareaOperationCompleted(object arg) {
            if ((this.ObtenerTareaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerTareaCompleted(this, new ObtenerTareaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice/", ResponseNamespace="http://webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ObtenerProyecto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Nombre) {
            object[] results = this.Invoke("ObtenerProyecto", new object[] {
                        Nombre});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerProyectoAsync(string Nombre) {
            this.ObtenerProyectoAsync(Nombre, null);
        }
        
        /// <remarks/>
        public void ObtenerProyectoAsync(string Nombre, object userState) {
            if ((this.ObtenerProyectoOperationCompleted == null)) {
                this.ObtenerProyectoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerProyectoOperationCompleted);
            }
            this.InvokeAsync("ObtenerProyecto", new object[] {
                        Nombre}, this.ObtenerProyectoOperationCompleted, userState);
        }
        
        private void OnObtenerProyectoOperationCompleted(object arg) {
            if ((this.ObtenerProyectoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerProyectoCompleted(this, new ObtenerProyectoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void USPROYCompletedEventHandler(object sender, USPROYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class USPROYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal USPROYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RegistrarseCompletedEventHandler(object sender, RegistrarseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void IniciarSesionCompletedEventHandler(object sender, IniciarSesionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IniciarSesionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IniciarSesionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void PublicarEstadoCompletedEventHandler(object sender, PublicarEstadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PublicarEstadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PublicarEstadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerIDEstCompletedEventHandler(object sender, obtenerIDEstCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerIDEstCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerIDEstCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void obtenerIDUSCompletedEventHandler(object sender, obtenerIDUSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerIDUSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerIDUSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void desplegarEstadosCompletedEventHandler(object sender, desplegarEstadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class desplegarEstadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal desplegarEstadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void BackupUsuariosCompletedEventHandler(object sender, BackupUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BackupUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BackupUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void BackupAsoCompletedEventHandler(object sender, BackupAsoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BackupAsoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BackupAsoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void PublicarComentarioCompletedEventHandler(object sender, PublicarComentarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PublicarComentarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PublicarComentarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void desplegarUSCompletedEventHandler(object sender, desplegarUSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class desplegarUSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal desplegarUSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CrearListaTAREACompletedEventHandler(object sender, CrearListaTAREACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearListaTAREACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearListaTAREACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CrearTareaCompletedEventHandler(object sender, CrearTareaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearTareaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearTareaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CrearProyectoCompletedEventHandler(object sender, CrearProyectoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearProyectoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearProyectoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ObtenerTareaCompletedEventHandler(object sender, ObtenerTareaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerTareaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerTareaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ObtenerProyectoCompletedEventHandler(object sender, ObtenerProyectoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerProyectoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerProyectoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591